### PR TITLE
Add event search, payment_intent events, and off_session 3DS

### PR DESCRIPTION
**Pull request by bpcreech**
A few different small things in this commit:

1. Add support for querying events by type and creation date.
2. Produce payment_intent.succeeded and payment_intent.payment_failed events
3. Add a simulation of a canonical Stripe test card that supports 3D Secure in off_session mode, if the configured properly with a setup_intent beforehand. This includes addition of a test-only _authenticate endpoint for setup_intents similar to the one that already exists for payment_intents.

### CODE REVIEW

**Review by adrienverge — COMMENTED** [review]
Hello @bpcreech, thanks again for contributing :+1:

Before we look into this, could you split these 3 changes into 3 different commits and/or pull requests (that you can open in parallel)? It both eases review and makes debugging / reverting much easier in case of a bug in the future.

**Comment by bpcreech** [comment]
Ah when you said you wanted more at once I thought you wanted a giant PR, not simultaneous PRs, got it, makes sense!

I filed https://github.com/adrienverge/localstripe/pull/239 which combines just 2 related event things, which are hard to separate because they're tested together. Let me know if that's acceptable.

Will send another for 3DS which is definitely decoupled.

**Comment by bpcreech** [comment]
Also https://github.com/adrienverge/localstripe/pull/240 for the 3DS part!

**Comment by bpcreech** [comment]
also https://github.com/adrienverge/localstripe/pull/241 for a tiny thing about refunds!

**Comment by adrienverge** [comment]
> Ah when you said you wanted more at once I thought you wanted a giant PR, not simultaneous PRs, got it, makes sense!

Hehe sorry for not being clear!

Indeed, it's easier to track / review / understand in separated PRs, and we can easily test them all together using `git merge` if needed.

**Pull request closed without merging**
