### PR TITLE
Add missing metadata to SubscriptionItems

### LINKED ISSUE #170: SubscriptionItem metadata not saved during Subscription creation
While using `localstripe` I found that the metadata was not being saved when a subscription was created with `items` specified.

### PR DESCRIPTION
**Pull request by t3hmrman**
Resolves #170

### CODE REVIEW

**Comment by t3hmrman** [comment]
Hey @adrienverge I'm not sure why the build is failing -- Travis reports an exit code of 0 (after the lastest commit ca12c18), but it's reporting as a failed build... I looked at the log and I'm not sure exactly what is wrong in the output...

**Comment by adrienverge** [comment]
Hello @t3hmrman,

The log is usually pretty clear: what's wrong is displayed in red:
```
$ if [[ $TRAVIS_PYTHON_VERSION != nightly ]]; then flake8 .; fi
./localstripe/resources.py:2590:80: E501 line too long (80 > 79 characters)
The command "if [[ $TRAVIS_PYTHON_VERSION != nightly ]]; then flake8 .; fi" exited with 1.
```

Can you please make one consistent commit and remove the README from the PR? It's not related to the fix, and I'm not favorable to make the README more complex with Docker instructions.

**Comment by t3hmrman** [comment]
Hi @adrienverge done and done -- thanks for pointing out the issue and thanks for the work on this project.

**Comment by adrienverge** [comment]
@t3hmrman it looks like the build is still failing for the same reason. I suggest moving all `SubscriptionItem()` arguments to the next line.

**Comment by t3hmrman** [comment]
@adrienverge fixed and squashed -- tests are green now

**Comment by adrienverge** [comment]
Sorry to see this too late, but you should instead use `items[0]['metadata']` and check the value (or set it to `None`), like for other properties of `items`:
- https://github.com/adrienverge/localstripe/blob/591f3b5a62eccfbe86ac24a2b937dc047a46095a/localstripe/resources.py#L2353-L2364
- https://github.com/adrienverge/localstripe/blob/591f3b5a62eccfbe86ac24a2b937dc047a46095a/localstripe/resources.py#L2546-L2559

**Comment by t3hmrman** [comment]
Hi @adrienverge I've just added the checks, squashed again

**Comment by adrienverge** [comment]
Thanks but like my previous comment says, you should now use `items[0]['metadata']` on lines 2419 and 2597, like for other properties.

**Comment by t3hmrman** [comment]
Ahh didn't get what you meant -- updated and re-squashed

**Comment by adrienverge** [comment]
Thanks for your contribution @t3hmrman!

Merged with a slight change:
```diff
@@ -2590,12 +2590,11 @@ class Subscription(StripeObject):
                     self.items._list[0].quantity != items[0]['quantity']):
                 self.items = List('/v1/subscription_items?subscription=' +
                                   self.id)
-                item = SubscriptionItem(
-                    subscription=self.id,
-                    plan=items[0]['plan'],
-                    quantity=items[0]['quantity'],
-                    metadata=items[0]['metadata'],
-                    tax_rates=items[0]['tax_rates'])
+                item = SubscriptionItem(subscription=self.id,
+                                        plan=items[0]['plan'],
+                                        quantity=items[0]['quantity'],
+                                        metadata=items[0]['metadata'],
+                                        tax_rates=items[0]['tax_rates'])
                 self.items._list.append(item)
 
                 # Create unused time pending item.
```

**Pull request merged**
